from enum import StrEnum


class IndicatorType(StrEnum):
    OPEN = "OPEN"
    HIGH = "HIGH"
    LOW = "LOW"
    CLOSE = "CLOSE"
    VOLUME = "VOLUME"
    SMA = "SMA"
    EMA = "EMA"
    RSI = "RSI"
    RETURN = "RETURN"
    N_DAY_RETURN = "N_DAY_RETURN"
    N_DAY_HIGH = "N_DAY_HIGH"
    N_DAY_LOW = "N_DAY_LOW"
    VOLUME_SMA = "VOLUME_SMA"
    DAY_OF_WEEK = "DAY_OF_WEEK"
    MONTH_OF_YEAR = "MONTH_OF_YEAR"
    CONSECUTIVE_UP_DAYS = "CONSECUTIVE_UP_DAYS"
    CONSECUTIVE_DOWN_DAYS = "CONSECUTIVE_DOWN_DAYS"
    GAP_RETURN = "GAP_RETURN"
    N_WEEK_HIGH = "N_WEEK_HIGH"
    N_WEEK_LOW = "N_WEEK_LOW"
